[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "0d8a34113185c694d1c76ab2fa69ecfb3d8e344b"
libgfortran_version = "5.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "598cd512d48a7e479e46ededdf41b360afeaf8c216bc53c01fadc7d90b525cf6"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-apple-darwin-libgfortran5.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "4138c864d9279ab6101ff0cf81ac9ea6562971b3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "71abb20a4a9a3834077e51e7b9dbc809ad3e5d5779a192a1d844a897b31b7ebb"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "117d9b502efd3dc0e5d9411ffe692ae43e75307e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "c5f1e7079c71a1c224a9ec8fde564e42cb4f380265655ce5c8931f22e3b726c8"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "e19b203fb8c6620ccc351c7d80ce992e2a5961cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "eeda77d1d384e585ec46cb406289968ef204aa8453585d755ec57cb17e05e373"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "a573936146bcd6312328fe2e0c1da6da8d967c9c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "ca2dbb191611ad1eace10983e68a6e52ed23c7995c03e2615b04573bbbf9dd1c"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "c6630d9db6e40c875837dd5c2bd1807568282e20"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "fbba9a67110a228532200df595b240598f6d496865ec151b421acbada3ccf8cd"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "e407dbcfb9dd8b45dcbb3a058510513dffaff251"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "da82f4ba53dfb3cc50edb097d77c6abc07e1169bf865714568a09ccb364625b2"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.aarch64-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "970a331208a8a1c7fe6b799bb7929fefe92a3a10"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "ff720f490db5b3041d3341a33a683b8a5349a179e6fdebbdbb2f3519863a1c49"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "309e47f9b86795af6f9eb3a86f386cd98402df28"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "aef6b6ffb07664d692064f88538fa948c23c31a5aeb5fac64d160a71cdd7b3ec"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e199076e2b8817142dc23cd4fb855aa45800bfd3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "fba77cdee9db32e5bb8e50bf29d68f3819f305b9bb7b322e4d869248294ab9cd"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccc4c053521d71f6ad8c708fde9c3ccb4d7525a1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "bec39e0f5fc713059e9af9ff0cb00e41c19fed36fd7bf8d68ae6c02754b310a4"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "079f96896e028b6ec55e4bb7048711973bb160c6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "4a6d0ec5868ddabf330569ad91de2c648b970e3b161075d2c3d18e7ce4ea5ca5"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ae64c95bf0e1733a2e353b5094a38701a0a724f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "f3844c9411982ebc95c45037e4d79d24aa7e79009d507a5daeade52576294b19"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e27d2e016002ccc8f396cc6997c8bec47be8521"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "2dda7882c35bf6b504f00c188eaf576eb4bdc25a3a0322d09fa2f1d620f5a6b4"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef0f09935192daccc479a4eaed7993352bd7dabe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "8e63a89bf21eda79af22f92d973ce71ec38963a9fa71e1ee1866a829f3617acf"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d737dafc3e767a6a48aa147cf34b54eca3f4755e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "7fec0b684b25e3621bc41d8c85230cfa90a65bba6960cabd7fd0701ea2b9a7b0"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96f7cd9a3b88839f2ff517310dba2b5a65f0d450"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "107da0ed753bce37471064303888102d63a508eb0284f4aa15a2d79ad1f6f231"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1622f1f0e2bd2b6880b9d618aed61d3e546f00ff"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "ae366129676c2ee0ea0a11fe9699e38aee7307f411ab21a48bf7f8510eb72479"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dcb07f029315213818a30d229387cf9d04b58ef9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "fd5a50ec4c122fcf3397a0418cbce19c769b563d2b82c135fe6727eac1fbac16"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "794f5b38977d8271802fbc6148e15cd3595a8d22"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "65f739ad242aa151dde0c6791c1219859914a3e4f02d68ee26be19742a33bac5"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "f42f65d9f872c0ff077f31e32927e3e67eee0818"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "27a715111b4d8987ad5ed168382e748acb82bd47cb74bd441058a98f1b1c4209"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "9c1f771d18ca050f388b3e8a561e9a710b034ab3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "a0e4acab1f9dffacbe598218ee038ba123f5ef41ef80107b2030f6090ee0e432"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "621bd1b2591196790108e19d589333dc48be00f4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "8fcc2a9aed0c874d73106c0dc6ced80e621d1fcf802052ca41aedbec19ff3755"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "b09d286185b3143ddde91a1f9dbdd92b41a55b95"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "3b37ff69d4706d58640f69e1af89ba82b9e3a871705faf5bb9f57f481432156c"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "462bae1fc705c1364c5c3abdcecd05390fc26563"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "91355cc23bf892f83cb40f68f1fa72eed7d7bfe3825535db6e9c0439a5c61326"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "4168747f30139b559b2cae17286ccec32381455b"
libgfortran_version = "3.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "e8bd279e2903ee7aebc99d086aaf209adcf13fa20327ece35cf1beaeb6940400"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "c479b30aaef423cab57940a155a2dd31966d3934"
libgfortran_version = "4.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "4e30ae316ca65b7c31ae101b64212b5efb6bc39067e82ff966203eae26cd8f8d"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "4a8c4096952534fe7fc9e4f5e0f558b9aed04054"
libgfortran_version = "5.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "67978c7c38efbe61637ab11dc2fb3fccdba4950921f8d70bc0853086e305c34c"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "832387907c2be6b07100537d08f064df1403ceee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "9b959a23f68cf313e59fdbef75e327925120c946ddd77156174893e3fdc7b372"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "76cee24d55b4771081736b390dd5f04a959bef35"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "25ba52ec36559952ac135e5868ee7f8e75325c1f48bbc830f2a9a1194094599d"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "0ee38c2a438d07fc9e59e98f4c923d94bca3159b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "071d269ae9a0eb5c8732bfc8a0d73866a955984504812874de20e7e87b74410f"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "ee4bd778f74a9d5fac290d083f61e7af6527ada1"
libgfortran_version = "3.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "121da36dd2c34f643282302761a9f4f7b83e5e5d2363f10753f9f8fb1f5abf7d"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-apple-darwin-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "744107692da9ceb250cf524649e150abc5141e43"
libgfortran_version = "4.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "8a3d1c4fd675ecad861f512e3b8402f05b3c497ae707efc09957aac34477c9a5"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-apple-darwin-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "842d458f692fe685865b9516f73df085db92ef3d"
libgfortran_version = "5.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "670d24dc09d57d38600b7f13901b5bda39f500aed1517b2fd545aafa63d21131"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-apple-darwin-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "838e021fc0798fe74f2d80717d046f25eb40d319"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "d2277b9b7c8897643f6042479357eb4783df5bd05d973cff7e0678d18e3da0de"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "6b870e9590ec9f6a7eb89769f64712fdc86af7aa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "74ff5083c84bd6740e1c655edf3b0d83765c33bd6261740c961dfc3f587463d3"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "18716554d448f94bdbfc191dab0a912d6cea74cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "a6d218f1068047bcaf66122425e73fd3d390b59a790a3fb49a8f8225899c3b60"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "83e9d152b49c3f36849d8cc886ccf1dd2259ff58"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "513879916956657f558c36fc7c3452428bba22bb76f38690980b789b62942958"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "fbff2b2f7e43038017327173e621f5db133575ba"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "bc4d3c64bbb23c6dde2f92566757f9b3b7cecdd8e30baedcead0032ed4fe1d4e"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "c62f58d0d4a77db3c6292082b332c44a42882416"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "98e531be95cafc39e516b306a93c746cf996467489be35214998b54010963a96"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "c851d939a838ed1128e21802e89db780fb2b5b78"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "409b12121e6e2625c698dfaf592b9bf5de2351d10debcd094f4399602b71d784"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "707242dda0faf8a5cdf6d54f6fe2e3e7805b23ac"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "71c3932fce76ebff0e323bc6be6d322781e58aea19343aafd55df33ce9b5b4ae"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "f3466b7ca68fd1d0d3367db78b3fd583236038c1"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "4e0fe8d8ea8daf99199bfea13f538cccc1e9c9a3bb1ca27fb1539de1a77e4da7"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "62adfd1673742739ae1229922f5fc23aa9e77ab8"
libgfortran_version = "3.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "7059f25725bce391e2516fc879707acd019f5aedd798bc8f79fc5550755ab975"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "776ffa2b72d516cbca636c5571fdc5082c651931"
libgfortran_version = "4.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "89b1f678ae269aef2bc67336b7216862998d9217d9af7c8fb8194c3b6a9b711d"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "4381739ddb586f9e5753b9caca40a8704b36930b"
libgfortran_version = "5.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "26b841c416f476af953da8ce21879bd5f3ec6362ba279abad091a18cb1263c78"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v2.0.13+0/glmnet.v2.0.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
