[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "8a959b5c67a1f0f2b4552aade22e68dd92a51c41"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "bb6bab45c966c82093fcde3c643b9581f72c9924ee9612bbd8ae3d943de87a7e"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "71acc71cc01b78d602d4ade9b27466df039565e7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "54fb4fec12d28d5f5e391fd1e7f8fd7fdbf85cad9396d7a2ccd267e5a351c410"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "3da345f075520954150f81731b9c45751490960e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "f16146184632fd57acedb4353c59b7d5177e3ad9048faeb432e1bbee1e046ae9"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "efae8bd059a225a9f5b514b79bf484402e9f805e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "a4f78a4eee3c942138269a5c3361b1dae26305028ebaecc75a7f14f9b659ba37"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "3d0b3d0d4bb6d484a3e41352425e1e93e04865f4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "1ad6c10c0841a56c8e90c70e5985532c0d1f1879e6cbf58c6baa09de089c2f88"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "aarch64"
git-tree-sha1 = "41599e9363117c4f1ccda3d8e60323af03edfac7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "06d0236e23c875c7d9e9a9ce73f5a0cc1f687f2f789473a312a1752bc1a60204"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e74e591f27ce55a7b976966053d27ad372e4ba1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "b48fc61f433ffb326ca1da0ef03a32b50a70c20a9d36c0f5cf8b9d7b56e2ad14"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce7f83a46093d18fc5beb29441da4dd8efa7ee5c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "f706a7751545e3852eed3efa84bcd3c3ba852abc3f1340b031a20135057b063a"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c1e4bd32b82c6c47e9dc13ff12babdb758c7b2d9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "ec06c47a0f5dee14bfec8e77786fab990bc4f2dbb6351717e223986a383cd805"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af075c13c140f52ab409f8f1b51d8ddf30f63ebd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "01aacd8e82a8ce93b62fe6b62e32550a4cf60175632821f4fc818ea9085fe765"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e2c1fe1f9a018f149a7bc3787f319d43707c004"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "f5c2c904c5ac8a9ff2b9fab74b4b8c2e9472eb494f87fbc356d9355a4fd5da0e"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[glmnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f143e1ff1b44f0a5b1072a9f5126511d7f10b37"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "26d0d26fc2387f79442086d671e639f10df883021d03a2e06059e4a59e4e0a67"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "48b5ac8448216b5233d46f83fd727d8fe28d6828"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "4ca929eb721bcdf965a3d4477f47a17ec6ed4d791ac69b14fb895b3842980f14"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "f42bc6e98c6f97a90b9c508cd7c8248be55321d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "4c3b26ad412f5788c9959d436a5b6524abe5ca30402d587468560d412cb2e9f8"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "4d2a8de639095baf87ceee1851bda741ed7ddf65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "033ec49a1cff197a34441609c10cecab93c22d9257298514a20d36699e4488de"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "b87d933643edbb49338b0e89ca99e554272f3586"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "4581b69293caed689f3e134ec8658e2f4d4d913829f741a894d78e7a4d33ae61"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "94fff778ef849c99305653528a8325374c698fe4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "0b2d4822b9808080a61b3a1b87b742b1b67f512a24f6798efcbf4dc35587dfcb"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "11e0beff58d871aa8fa7c96a827ee202b6f222c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "eaa4b951c83bbcc6a7a2e72f1b8e2717feb3df2bc4e581477927b51dcca15e3b"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "6c8e8c9c6e768269f3b4667658996ef0db6476fc"
libgfortran_version = "3.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "14d41c134a0e3eecadad6e0297f83c396e8dc2148c50542e85e517ff39b61988"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "aca474e7bba8e988cfe66db688b9a3f96a8661de"
libgfortran_version = "4.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "5ee7bdcf597437d9f4d8c5937720bd901bbbf76b5e4d46d9a31161bdfbbe31db"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[glmnet]]
arch = "i686"
git-tree-sha1 = "2de8dd8e01143036e3678bcde05501bbdd87f6fd"
libgfortran_version = "5.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "65a5c4814a1bd7f9dc868b54cf0650681b24773b0d7b4b21075c0c1400260193"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "1046169d55a88d79bdc356f911ccdec1464c9a79"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "9d738df7979553c92e5e47864c43a8ba42054ed18b045fcb9c5be14e052998b6"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "570757f1371da53acf0acc2362744975f99c89ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "1c35d6301e17fca7acf6b412db8586d01105be78101795fe465e5543b8cba344"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "powerpc64le"
git-tree-sha1 = "966d11e4f517110e8de552b01a59058646aed298"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "8baadd355def1cbb032419ce9362d544880e98dd75f044cb1efc64155158c56a"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "fa29b86183f1c59cb46197d720a56a67887a4336"
libgfortran_version = "3.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "96a7dd862f7560d50bbd91b1dfd3e916adb2b3ace8b796b20a6feef48472bd97"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "5d34731b8439fbc8c1fd471fb660af32904d6867"
libgfortran_version = "4.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "a2682518ac6dbd95bbc79a45b46da3fdca89407bf27b4d8f75fdc4a51dd1d585"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "d02e20d592882313129f6513f4382bc974134210"
libgfortran_version = "5.0.0"
os = "macos"

    [[glmnet.download]]
    sha256 = "21d438f55b19e0f80b5999abb7f0edcfa6cd829c557356f6408167caecc103d4"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "383e73b51f5db98209d359d56ec0e46d0141e9c6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "0ddf7f9844f4c46f11dcfa9df13d97030530117ddc70f47714f7d03fa9e64809"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "1a06cddb6d26a362bbe90fbe395736b47d9728c5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "c9c0da1a09a976de3e75e6da1b11bc8e7bdec17cf36fc69f88ef2c542f214868"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "da6fcd9cf94647e00cb654af61945deeea0757c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "6ec9199c6f567d2ac081e3fc7865474ace0dcf2be24b8edb1fe369d8827fa8c9"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "8454e61d7238e676b28c8bea97d5516c04863c40"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "79df4ae1d76f662e6320df6966485580475e40f3f3a8b9ea5e7357f18b5cd913"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "0f02c0a769f0e83e03181b8df07b011def4b59ae"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "5a5c3c5972a7a03400bde49dc2997addefd8ffd9759ae6d14c309bea32deb107"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "fa147f08193c04f43c82c92a71a2947673ce3d86"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[glmnet.download]]
    sha256 = "156f8d865747c8d49948d980ff3ee00a6c3a61389d45ead5a72be4ce519732b4"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "061bb27a572f37fc82a97072b6ec5f9731785ac3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "43902b336a18991f579933431ecdff358c20bf35a1384c37c6c927c1569edbec"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "ad2670fcd5587118858e98e8eecd711e68ebb72b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "513957ed61c8551d6feb4bdb2cd69ccde3d07e51857b6c4f318bd9ec6d8827e7"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "b48d9033ecebf940a3ce348c6af5ba4986703a75"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[glmnet.download]]
    sha256 = "3bd388207706536e56bb1826d37d6f73da2c9b629774f29e1edcbb3a496118f7"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "8b431cdf6880902369c55c3d22e8c85e9f622c35"
libgfortran_version = "3.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "b87ab08cfa781122ffb42e4b6260c49e1353efe19f20a5b03e22611801381e5f"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "35cacccd6a2d0e7b39e4223a5faed6540265c9d7"
libgfortran_version = "4.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "fcfc76c51ebf4301b1e84477ec3321c8dbb212c9c17992869c4733199715a4a3"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[glmnet]]
arch = "x86_64"
git-tree-sha1 = "5b5961c2da99d62f86b842dd477510f61eec241a"
libgfortran_version = "5.0.0"
os = "windows"

    [[glmnet.download]]
    sha256 = "75aab34b448b3fec9e26f23f864dd3f379c8dd523f8a93fd77b4452ce444532a"
    url = "https://github.com/JuliaBinaryWrappers/glmnet_jll.jl/releases/download/glmnet-v4.0.2+0/glmnet.v4.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
